// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/inari111/layered-architecture-example-2020/handler/api"
	"net/http"
)

// Injectors from api.go:

func InitializeAPIHandler() http.Handler {
	taskService := api.NewTaskService()
	handler := api.NewHandler(taskService)
	return handler
}
